### ISSUE TITLE
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by chinnumerinmathew** [HackerHouseYT/Smart-Security-Camera#11]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/pi/.local/lib/python2.7/site-packages/imutils/video/pivideostream.py", line 31, in update
  File "/home/pi/.local/lib/python2.7/site-packages/picamera/camera.py", line 1710, in capture_continuous
  File "/home/pi/.local/lib/python2.7/site-packages/picamera/encoders.py", line 431, in close
  File "/home/pi/.local/lib/python2.7/site-packages/picamera/encoders.py", line 413, in stop
  File "/home/pi/.local/lib/python2.7/site-packages/picamera/encoders.py", line 357, in active
  File "/home/pi/.local/lib/python2.7/site-packages/picamera/mmalobj.py", line 776, in enabled
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

#the object is not detected while running the video in the server

**Comment by PedroMiguelSimoesMiranda** [comment]
chinnumerinmathew were you able to resolve this? I am experiencing the same issue! The camera works, it pops up in the browser but it does not detect faces
