### ISSUE TITLE
Exception AttributeError: "'VideoCamera' object has no attribute 'vs'" 

### ISSUE THREAD

**Issue by Devraj004** [HackerHouseYT/Smart-Security-Camera#20]
Hi Friends,
I have installed the code successfully. But when running python main.py file getting attribute error.

Any help please ?

* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x2378020 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    video_camera = VideoCamera(flip = True) # creates a camera object, flip vertically
  File "/home/pi/Smart-Security-Camera/Smart-Security-Camera/camera.py", line 9, in __init__
    self.vs = PiVideoStream().start()
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/imutils/video/pivideostream.py", line 10, in __init__
    self.camera = PiCamera()
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/camera.py", line 433, in __init__
    self._init_preview()
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/camera.py", line 513, in _init_preview
    self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/renderers.py", line 558, in __init__
    self.renderer.inputs[0].connect(source).enable()
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/mmalobj.py", line 2212, in enable
    prefix="Failed to enable connection")
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources
Exception AttributeError: "'VideoCamera' object has no attribute 'vs'" in <bound method VideoCamera.__del__ of <camera.VideoCamera object at 0x7069eef0>> ignored

**Comment by kumar4Vipul** [comment]
did anyone found the solution?

**Comment by kumar4Vipul** [comment]
In main.py file
if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8000, debug=False)
debug need to be set to False
https://raspberrypi.stackexchange.com/questions/51406/cannot-connect-to-picamera-when-using-it-with-flask

**Comment by donaca4555** [comment]
not sure if it's connected.. I've got the same error when tried running a flask picamera proccess with node execSync. running it with exec solved it in my case.

**Comment by hadi-source** [comment]
> not sure if it's connected.. I've got the same error when tried running a flask picamera proccess with node execSync. running it with exec solved it in my case.

can you please elaborate it
