### ISSUE TITLE
no module named error

### ISSUE THREAD

**Issue by CluelessCoderNYC** [HackerHouseYT/Smart-Security-Camera#3]
ok so to start im a beginner and this is my first raspberry pi project, anyways when i try to run the script im getting this error. can anyone help 

(cv) pi@raspberrypi:~/Smart-Security-Camera $ python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from mail import sendEmail
  File "/home/pi/Smart-Security-Camera/mail.py", line 2, in <module>
    from email.MIMEMultipart import MIMEMultipart
ImportError: No module named 'email.MIMEMultipart'

**Comment by thomfort** [comment]
Yep, I got the same error, you need to change for this:

> from email.mime.multipart import MIMEMultipart
> from email.mime.text import MIMEText
> from email.mime.image import MIMEImage

**Comment by atainter** [comment]
Are you running python 3?

**Comment by thomfort** [comment]
yep

**Comment by atainter** [comment]
Will add it to the README

**Comment by thomfort** [comment]
They have other errors, if you run python 3, you need to change all print method with quotation marks for parentheses.

print ""  => print()

**Comment by CluelessCoderNYC** [comment]
Yeah thomfort I had the same errors there too I had to go in and add parentheses. Again I'm a total beginner but for as good of production quality of the YouTube video was for this project I didn't expect there to be so many issues please if you guys figure out how to fix this let me know

**Comment by Kowus** [comment]
I'm getting a similar error but for cv2

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import cv2
ImportError: No module named 'cv2'

**Comment by rarenu** [comment]
Dear Mr. Attainter, I am also having same error, please advice.
(cv) pi@raspberrypi:~/Smart-Security-Camera $ python3 main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from mail import sendEmail
  File "/home/pi/Smart-Security-Camera/mail.py", line 2, in <module>
    import MIMEMultipart
ImportError: No module named 'MIMEMultipart'

**Comment by kazkaif** [comment]
kowus same problem here

**Comment by ambergl2014** [comment]
main.py says cv2 file missing

**Comment by tumpa** [comment]
I am having an error compiling with python 2.7
ImportError : No module named imutils.video.pivideostream in camera.py

**Comment by purvaavrup** [comment]
from camera import VideoCamera
ImportError : No module named 'Camera'

I am getting this error while running camera.py in python3
